language: c
compiler: gcc
dist: xenial
addons:
  apt:
    packages:
    - libreadline-dev
    - zlib1g-dev
install:
  - curl -L https://cpanmin.us | perl - App::cpanminus
  - ~/perl5/bin/cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - ~/perl5/bin/cpanm IPC::Run
  - ~/perl5/bin/cpanm Test::More
  - ~/perl5/bin/cpanm Time::HiRes
script:
  - export CFLAGS="-Og"
  - ./configure --enable-debug --enable-cassert --enable-depend --enable-tap-tests BISONFLAGS="-v"
  - make check-world
